# Generated by Django 4.1.7 on 2023-07-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('category', models.CharField(default='category', max_length=100)),
                ('muscle', models.CharField(default='muscle', max_length=100)),
                ('muscle_joint_group', models.CharField(default='none', max_length=100)),
                ('difficulty', models.CharField(default='Beginner', max_length=20)),
                ('beginner_reps', models.CharField(default='2 x 10', max_length=20)),
                ('intermediate_reps', models.CharField(default='3 x 10', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ManyToManyField(to='jacob.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
