# Generated by Django 4.1.7 on 2023-07-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='beginner_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='intermediate_reps',
        ),
    ]
