# Generated by Django 4.1.7 on 2023-04-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0003_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='exercises',
            new_name='exercise',
        ),
    ]
