# Generated by Django 4.1.7 on 2023-04-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0004_rename_exercises_program_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='bodypart',
        ),
        migrations.AddField(
            model_name='exercise',
            name='compound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='isloation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(default='muscle', max_length=100),
        ),
    ]
