# Generated by Django 4.1.7 on 2023-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0005_remove_exercise_bodypart_exercise_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_joint_group',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
