# Generated by Django 4.1.7 on 2023-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0006_exercise_muscle_joint_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='isloation',
        ),
        migrations.AddField(
            model_name='program',
            name='day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
