# Generated by Django 4.1.7 on 2023-07-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0007_remove_exercise_compound_remove_exercise_isloation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='beginner_reps',
            field=models.CharField(default='2 x 10', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='intermediate_reps',
            field=models.CharField(default='3 x 10', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='experience',
            field=models.CharField(default='beginner', max_length=20),
        ),
    ]
