# Generated by Django 4.1.7 on 2023-07-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0008_exercise_beginner_reps_exercise_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=20),
        ),
    ]
