# Generated by Django 4.1.7 on 2023-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0009_alter_exercise_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='experience',
            field=models.CharField(default='Beginner', max_length=20),
        ),
    ]
